# Generated by Django 5.0 on 2023-12-10 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='file',
            field=models.FileField(default=False, upload_to=''),
        ),
    ]
